a = float(input("Nhập số a: "))
b = float(input("Nhập số b: "))
kq1= a + b
kq2 = a - b
kq3 = int(b - a)
kq4 = a * b
kq5 = a % b
kq6 = a /b
print("Tổng %d + %d = %d"% (a, b, kq1))
print("Hiệu %d - %d = %d"% (a, b, kq2))
print("Hiệu %d - %d = %d"% (a, b, kq3))
print("Tích %d * %d = %d"% (a, b, kq4))
print("Chia lấy dư %d %% %d = %d"% (a, b, kq5))
print("Thương %d / %d = %d"% (a, b, kq6))